using FindMaximumValue;
Console.WriteLine("Welcome to Generics program to find the maximum of three values");
int[] intArray = { 4, 3, 2, 1 };
double[] doubleArray = { 1.765, 1.234, 1.345, 1.534 };
string[] stringArray = { "22", "25", "27", "29" };
Find<int> check1 = new Find<int>();
Find<double> check2 = new Find<double>();
Find<string> check3 = new Find<string>();
check1.ToCompare(intArray);
check2.ToCompare(doubleArray);
check3.ToCompare(stringArray);